In [44]:
import os
import csv

In [2]:
os.getcwd()

'/Users/jaewook.lee/github/X-tools'

In [3]:
import csv

In [4]:
with open("xangle_template_unlockschedule.csv") as file:
    reader = csv.reader(file)
print(reader)

<_csv.reader object at 0x1050ee9e0>

In [2]:
import pandas as pd

df = pd.read_csv("xangle_template_unlockschedule.csv")

In [3]:
df.shape()

TypeError: 'tuple' object is not callable

In [4]:
df

,Unnamed: 0,xpla1vnzz7xyqjaayljtdrug845tdlw33k2pnh47k4e,xpla1j0rc0uraryz205ulycxv7t8a05q35rvpncz3jw,xpla1e8xzemhx36xp7qu2gtllgpcde2z8y498j2zyrk,xpla1qxfrqlf8tpz532w0t5gz76ud4qg398xrr29r65,xpla1vdqljayz7rm04xj9p4du2cgmf3jzfsa0ka9f7l,xpla1vrget09sfejz8l8q0jwucva7pl93at9x5hp8qg,xpla1mfe4yrwkyarsrvncnhw9unfqkjzwcyrj9dt72u,xpla10ksn9528f82uwnmz3sgr4n42l0nucmzntjrg00,xpla19dacf8gzsvuj9txzw0wmtfpdg8swpd4jxl3ks2,...,xpla1xwtrcm6huapy90mlckfhd4vw73x5j6wrzut9afhpmrhnkcy20dus02kf7n,xpla126402sucs3zwreams5adstmvlnzytuegcy2e2dav0g94e990803qudxw78,xpla18nd704wpeagscgg0qg5t9f7nxvdlm87j9255gzcmc73kr59xyd7qh8p9jr,xpla1mjx673u8jq6lmc3xqa2a86hjshnjt29znza62rwcz0hnmcr55qqqx0saff,xpla1jnxy3fdr3l8ck2uw0dnvnfy7mdlgxy2vgunv9k9584ajsjkf0qcszfpfug,xpla1asvgm5x6dm2k2m59pu6t750l0eqswddh8pjulqwe3kvk25tz9g4q640zex,xpla19fr3z4g04344aelwdjxl7vk73a6hec6tpz2m2x90d9ft2ra5sw7qrkmrap,xpla1tddsuf25rrjgl9ty9lazhxe38q66uva7eqak3qz2c8e4yk0gj0yqj23r94,xpla1pplj0vzv57xh64ydh5pkfpv6s0hyj3jxugdlezrl5j64wcyt9yyq2zkens,xpla1gcs4amt2aztnj5xrpprja050jg97ywsc90xh4ylvr6w2zj2f0v9q0vxwuy
0,2022/08/19,747249890,60000000,300000000,300000000,53137610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
1,2022/08/31,747249890,60000000,300000000,300000000,53137610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
2,2022/09/30,747249890,60000000,300000000,300000000,53137610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
3,2022/10/31,720857890,60000000,300000000,300000000,52932610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
4,2022/11/30,750953364,60000000,300000000,300000000,52732610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16378,1900/01/00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16379,1900/01/00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16380,1900/01/00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16381,1900/01/00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16382,1900/01/00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df[0]

KeyError: 0

In [6]:
df.shape

(16383, 23)

In [7]:
df_sliced = df.iloc[:55, :]

In [8]:
df_sliced

,Unnamed: 0,xpla1vnzz7xyqjaayljtdrug845tdlw33k2pnh47k4e,xpla1j0rc0uraryz205ulycxv7t8a05q35rvpncz3jw,xpla1e8xzemhx36xp7qu2gtllgpcde2z8y498j2zyrk,xpla1qxfrqlf8tpz532w0t5gz76ud4qg398xrr29r65,xpla1vdqljayz7rm04xj9p4du2cgmf3jzfsa0ka9f7l,xpla1vrget09sfejz8l8q0jwucva7pl93at9x5hp8qg,xpla1mfe4yrwkyarsrvncnhw9unfqkjzwcyrj9dt72u,xpla10ksn9528f82uwnmz3sgr4n42l0nucmzntjrg00,xpla19dacf8gzsvuj9txzw0wmtfpdg8swpd4jxl3ks2,...,xpla1xwtrcm6huapy90mlckfhd4vw73x5j6wrzut9afhpmrhnkcy20dus02kf7n,xpla126402sucs3zwreams5adstmvlnzytuegcy2e2dav0g94e990803qudxw78,xpla18nd704wpeagscgg0qg5t9f7nxvdlm87j9255gzcmc73kr59xyd7qh8p9jr,xpla1mjx673u8jq6lmc3xqa2a86hjshnjt29znza62rwcz0hnmcr55qqqx0saff,xpla1jnxy3fdr3l8ck2uw0dnvnfy7mdlgxy2vgunv9k9584ajsjkf0qcszfpfug,xpla1asvgm5x6dm2k2m59pu6t750l0eqswddh8pjulqwe3kvk25tz9g4q640zex,xpla19fr3z4g04344aelwdjxl7vk73a6hec6tpz2m2x90d9ft2ra5sw7qrkmrap,xpla1tddsuf25rrjgl9ty9lazhxe38q66uva7eqak3qz2c8e4yk0gj0yqj23r94,xpla1pplj0vzv57xh64ydh5pkfpv6s0hyj3jxugdlezrl5j64wcyt9yyq2zkens,xpla1gcs4amt2aztnj5xrpprja050jg97ywsc90xh4ylvr6w2zj2f0v9q0vxwuy
0,2022/08/19,747249890,60000000,300000000,300000000,53137610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
1,2022/08/31,747249890,60000000,300000000,300000000,53137610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
2,2022/09/30,747249890,60000000,300000000,300000000,53137610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
3,2022/10/31,720857890,60000000,300000000,300000000,52932610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
4,2022/11/30,750953364,60000000,300000000,300000000,52732610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
5,2022/12/31,744180393,60000000,300000000,300000000,52732610,300000000,40000000,20000000,60000000,...,120600,120371,228000,0,0,0,0,0,0,0
6,2023/01/31,742680393,60000000,0,200000000,52732610,0,0,20000000,60000000,...,104823,104624,198173,1500000,270000000,287500000,37125000,100000000,0,0
7,2023/02/28,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,95571,95390,180682,1940000,270000000,275000000,35000000,100000000,19600000,3000000
8,2023/03/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,85329,85166,161318,1900000,270000000,262500000,35000000,87500000,19600000,3000000
9,2023/04/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,75416,75273,142578,1860000,240000000,250000000,32125000,87500000,19600000,3000000
10,2023/05/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,65174,65050,123214,1820000,240000000,237500000,30000000,87500000,19600000,3000000
11,2023/06/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,55261,55156,104474,1780000,240000000,225000000,30000000,75000000,19600000,3000000
12,2023/07/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,45018,44933,85110,1740000,210000000,212500000,27125000,75000000,19600000,3000000
13,2023/08/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,34776,34709,65745,1700000,210000000,200000000,25000000,75000000,19600000,3000000
14,2023/09/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,24863,24816,47005,1660000,180000000,175000000,25000000,62500000,19600000,3000000
15,2023/10/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,14621,14593,27641,1620000,180000000,162500000,22125000,62500000,19600000,3000000
16,2023/11/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,4708,4699,8901,1580000,180000000,150000000,20000000,62500000,19600000,3000000
17,2023/12/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,1540000,160000000,137500000,20000000,50000000,19600000,3000000
18,2024/01/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,1500000,160000000,125000000,17125000,50000000,19600000,3000000
19,2024/02/29,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,160000000,112500000,17875000,50000000,19600000,3000000
20,2024/03/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,140000000,100000000,15000000,37500000,19600000,3000000
21,2024/04/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,140000000,87500000,12125000,37500000,19600000,3000000
22,2024/05/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,140000000,75000000,10000000,37500000,19600000,3000000
23,2024/06/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,120000000,62500000,10000000,25000000,19600000,3000000
24,2024/07/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,120000000,50000000,7125000,25000000,19600000,3000000
25,2024/08/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,120000000,37500000,5000000,25000000,19600000,3000000
26,2024/09/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,100000000,25000000,5000000,12500000,19600000,3000000
27,2024/10/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,100000000,12500000,2125000,12500000,19600000,3000000
28,2024/11/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,100000000,0,0,12500000,19600000,3000000
29,2024/12/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,85000000,0,0,0,19600000,3000000
30,2025/01/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,85000000,0,0,0,19600000,3000000
31,2025/02/28,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,85000000,0,0,0,19600000,3000000
32,2025/03/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,70000000,0,0,0,19600000,3000000
33,2025/04/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,70000000,0,0,0,19600000,3000000
34,2025/05/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,70000000,0,0,0,19600000,3000000
35,2025/06/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,55000000,0,0,0,19600000,3000000
36,2025/07/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,55000000,0,0,0,19600000,3000000
37,2025/08/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,55000000,0,0,0,19600000,3000000
38,2025/09/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,40000000,0,0,0,19600000,3000000
39,2025/10/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,40000000,0,0,0,19600000,3000000
40,2025/11/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,40000000,0,0,0,19600000,3000000
41,2025/12/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,30000000,0,0,0,19600000,3000000
42,2026/01/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,30000000,0,0,0,19600000,3000000
43,2026/02/28,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,30000000,0,0,0,19600000,3000000
44,2026/03/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,20000000,0,0,0,19600000,3000000
45,2026/04/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,20000000,0,0,0,19600000,3000000
46,2026/05/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,20000000,0,0,0,19600000,3000000
47,2026/06/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,10000000,0,0,0,19600000,3000000
48,2026/07/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,10000000,0,0,0,19600000,3000000
49,2026/08/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,10000000,0,0,0,19600000,3000000
50,2026/09/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,0,0,0,0,19600000,3000000
51,2026/10/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,0,0,0,0,19600000,3000000
52,2026/11/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,0,0,0,0,19600000,3000000
53,2026/12/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,0,0,0,0,19600000,3000000
54,1900/01/00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df_sliced = df_sliced[:54, :]

InvalidIndexError: (slice(None, 54, None), slice(None, None, None))

In [10]:
df_sliced = df_sliced.iloc[:54, :]

In [27]:
df_sliced

,Unnamed: 0,xpla1vnzz7xyqjaayljtdrug845tdlw33k2pnh47k4e,xpla1j0rc0uraryz205ulycxv7t8a05q35rvpncz3jw,xpla1e8xzemhx36xp7qu2gtllgpcde2z8y498j2zyrk,xpla1qxfrqlf8tpz532w0t5gz76ud4qg398xrr29r65,xpla1vdqljayz7rm04xj9p4du2cgmf3jzfsa0ka9f7l,xpla1vrget09sfejz8l8q0jwucva7pl93at9x5hp8qg,xpla1mfe4yrwkyarsrvncnhw9unfqkjzwcyrj9dt72u,xpla10ksn9528f82uwnmz3sgr4n42l0nucmzntjrg00,xpla19dacf8gzsvuj9txzw0wmtfpdg8swpd4jxl3ks2,...,xpla1xwtrcm6huapy90mlckfhd4vw73x5j6wrzut9afhpmrhnkcy20dus02kf7n,xpla126402sucs3zwreams5adstmvlnzytuegcy2e2dav0g94e990803qudxw78,xpla18nd704wpeagscgg0qg5t9f7nxvdlm87j9255gzcmc73kr59xyd7qh8p9jr,xpla1mjx673u8jq6lmc3xqa2a86hjshnjt29znza62rwcz0hnmcr55qqqx0saff,xpla1jnxy3fdr3l8ck2uw0dnvnfy7mdlgxy2vgunv9k9584ajsjkf0qcszfpfug,xpla1asvgm5x6dm2k2m59pu6t750l0eqswddh8pjulqwe3kvk25tz9g4q640zex,xpla19fr3z4g04344aelwdjxl7vk73a6hec6tpz2m2x90d9ft2ra5sw7qrkmrap,xpla1tddsuf25rrjgl9ty9lazhxe38q66uva7eqak3qz2c8e4yk0gj0yqj23r94,xpla1pplj0vzv57xh64ydh5pkfpv6s0hyj3jxugdlezrl5j64wcyt9yyq2zkens,xpla1gcs4amt2aztnj5xrpprja050jg97ywsc90xh4ylvr6w2zj2f0v9q0vxwuy
0,2022/08/19,747249890,60000000,300000000,300000000,53137610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
1,2022/08/31,747249890,60000000,300000000,300000000,53137610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
2,2022/09/30,747249890,60000000,300000000,300000000,53137610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
3,2022/10/31,720857890,60000000,300000000,300000000,52932610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
4,2022/11/30,750953364,60000000,300000000,300000000,52732610,300000000,40000000,20000000,60000000,...,0,0,0,0,0,0,0,0,0,0
5,2022/12/31,744180393,60000000,300000000,300000000,52732610,300000000,40000000,20000000,60000000,...,120600,120371,228000,0,0,0,0,0,0,0
6,2023/01/31,742680393,60000000,0,200000000,52732610,0,0,20000000,60000000,...,104823,104624,198173,1500000,270000000,287500000,37125000,100000000,0,0
7,2023/02/28,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,95571,95390,180682,1940000,270000000,275000000,35000000,100000000,19600000,3000000
8,2023/03/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,85329,85166,161318,1900000,270000000,262500000,35000000,87500000,19600000,3000000
9,2023/04/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,75416,75273,142578,1860000,240000000,250000000,32125000,87500000,19600000,3000000
10,2023/05/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,65174,65050,123214,1820000,240000000,237500000,30000000,87500000,19600000,3000000
11,2023/06/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,55261,55156,104474,1780000,240000000,225000000,30000000,75000000,19600000,3000000
12,2023/07/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,45018,44933,85110,1740000,210000000,212500000,27125000,75000000,19600000,3000000
13,2023/08/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,34776,34709,65745,1700000,210000000,200000000,25000000,75000000,19600000,3000000
14,2023/09/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,24863,24816,47005,1660000,180000000,175000000,25000000,62500000,19600000,3000000
15,2023/10/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,14621,14593,27641,1620000,180000000,162500000,22125000,62500000,19600000,3000000
16,2023/11/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,4708,4699,8901,1580000,180000000,150000000,20000000,62500000,19600000,3000000
17,2023/12/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,1540000,160000000,137500000,20000000,50000000,19600000,3000000
18,2024/01/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,1500000,160000000,125000000,17125000,50000000,19600000,3000000
19,2024/02/29,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,160000000,112500000,17875000,50000000,19600000,3000000
20,2024/03/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,140000000,100000000,15000000,37500000,19600000,3000000
21,2024/04/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,140000000,87500000,12125000,37500000,19600000,3000000
22,2024/05/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,140000000,75000000,10000000,37500000,19600000,3000000
23,2024/06/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,120000000,62500000,10000000,25000000,19600000,3000000
24,2024/07/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,120000000,50000000,7125000,25000000,19600000,3000000
25,2024/08/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,120000000,37500000,5000000,25000000,19600000,3000000
26,2024/09/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,100000000,25000000,5000000,12500000,19600000,3000000
27,2024/10/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,100000000,12500000,2125000,12500000,19600000,3000000
28,2024/11/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,100000000,0,0,12500000,19600000,3000000
29,2024/12/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,85000000,0,0,0,19600000,3000000
30,2025/01/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,85000000,0,0,0,19600000,3000000
31,2025/02/28,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,85000000,0,0,0,19600000,3000000
32,2025/03/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,70000000,0,0,0,19600000,3000000
33,2025/04/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,70000000,0,0,0,19600000,3000000
34,2025/05/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,70000000,0,0,0,19600000,3000000
35,2025/06/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,55000000,0,0,0,19600000,3000000
36,2025/07/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,55000000,0,0,0,19600000,3000000
37,2025/08/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,55000000,0,0,0,19600000,3000000
38,2025/09/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,40000000,0,0,0,19600000,3000000
39,2025/10/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,40000000,0,0,0,19600000,3000000
40,2025/11/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,40000000,0,0,0,19600000,3000000
41,2025/12/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,30000000,0,0,0,19600000,3000000
42,2026/01/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,30000000,0,0,0,19600000,3000000
43,2026/02/28,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,30000000,0,0,0,19600000,3000000
44,2026/03/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,20000000,0,0,0,19600000,3000000
45,2026/04/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,20000000,0,0,0,19600000,3000000
46,2026/05/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,20000000,0,0,0,19600000,3000000
47,2026/06/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,10000000,0,0,0,19600000,3000000
48,2026/07/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,10000000,0,0,0,19600000,3000000
49,2026/08/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,10000000,0,0,0,19600000,3000000
50,2026/09/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,0,0,0,0,19600000,3000000
51,2026/10/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,0,0,0,0,19600000,3000000
52,2026/11/30,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,0,0,0,0,19600000,3000000
53,2026/12/31,742242613,60000000,0,200000000,49732610,0,0,400000,59999850,...,0,0,0,0,0,0,0,0,19600000,3000000

In [12]:
df.columns

Index(['Unnamed: 0', 'xpla1vnzz7xyqjaayljtdrug845tdlw33k2pnh47k4e',
       'xpla1j0rc0uraryz205ulycxv7t8a05q35rvpncz3jw',
       'xpla1e8xzemhx36xp7qu2gtllgpcde2z8y498j2zyrk',
       'xpla1qxfrqlf8tpz532w0t5gz76ud4qg398xrr29r65',
       'xpla1vdqljayz7rm04xj9p4du2cgmf3jzfsa0ka9f7l',
       'xpla1vrget09sfejz8l8q0jwucva7pl93at9x5hp8qg',
       'xpla1mfe4yrwkyarsrvncnhw9unfqkjzwcyrj9dt72u',
       'xpla10ksn9528f82uwnmz3sgr4n42l0nucmzntjrg00',
       'xpla19dacf8gzsvuj9txzw0wmtfpdg8swpd4jxl3ks2',
       'xpla15nczwuqh0zcu6syeqsc4td6dphql7n2p7cgkl9raz97z5s3zdjrs0t3sta',
       'xpla1nphwrdqm9ky03c2eccmccrd3atg5usw9ltjn08he850xthxp7c0stg7tpc',
       'xpla1upd858fjdlme0wv4vd2v7c4majyr9dg53rl72dzfhds9zusmn9mq80m5p7',
       'xpla1xwtrcm6huapy90mlckfhd4vw73x5j6wrzut9afhpmrhnkcy20dus02kf7n',
       'xpla126402sucs3zwreams5adstmvlnzytuegcy2e2dav0g94e990803qudxw78',
       'xpla18nd704wpeagscgg0qg5t9f7nxvdlm87j9255gzcmc73kr59xyd7qh8p9jr',
       'xpla1mjx673u8jq6lmc3xqa2a86hjshnjt29znza62rwcz0hnmcr55qqqx0saff',
       'xpla1jnxy3fdr3l8ck2uw0dnvnfy7mdlgxy2vgunv9k9584ajsjkf0qcszfpfug',
       'xpla1asvgm5x6dm2k2m59pu6t750l0eqswddh8pjulqwe3kvk25tz9g4q640zex',
       'xpla19fr3z4g04344aelwdjxl7vk73a6hec6tpz2m2x90d9ft2ra5sw7qrkmrap',
       'xpla1tddsuf25rrjgl9ty9lazhxe38q66uva7eqak3qz2c8e4yk0gj0yqj23r94',
       'xpla1pplj0vzv57xh64ydh5pkfpv6s0hyj3jxugdlezrl5j64wcyt9yyq2zkens',
       'xpla1gcs4amt2aztnj5xrpprja050jg97ywsc90xh4ylvr6w2zj2f0v9q0vxwuy'],
      dtype='object')

In [51]:
df = df_sliced
date_list = df[df.columns[0]]

wallets = [address for address in df.columns[1:]]

for wallet in wallets:
    df_out = pd.DataFrame({'락업해제일자* (yyyy-mm-dd)': date_list, "락업해제수량*" : df[wallet]})
    with open(f"xpla/{wallet}.csv", 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerows(df_out.values)

In [34]:
df_out

0         0
1         0
2         0
3         0
4         0
5         0
6         0
7   3000000
8   3000000
9   3000000
10  3000000
11  3000000
12  3000000
13  3000000
14  3000000
15  3000000
16  3000000
17  3000000
18  3000000
19  3000000
20  3000000
21  3000000
22  3000000
23  3000000
24  3000000
25  3000000
26  3000000
27  3000000
28  3000000
29  3000000
30  3000000
31  3000000
32  3000000
33  3000000
34  3000000
35  3000000
36  3000000
37  3000000
38  3000000
39  3000000
40  3000000
41  3000000
42  3000000
43  3000000
44  3000000
45  3000000
46  3000000
47  3000000
48  3000000
49  3000000
50  3000000
51  3000000
52  3000000
53  3000000